name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read
  actions: read     # <-- needed to read workflow runs/jobs
  checks: read      # <-- needed to read check runs
  statuses: read    # <-- needed to read commit statuses
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Skip deployment if this is the template repository
    if: github.event.repository.name != 'workshop-template'
    env:
      REQUIRES_AUTH: ${{ secrets.REQUIRES_AUTHENTICATION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@nss-workshops'
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create env file
      run: |
          echo "VITE_OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" > .env
          echo "VITE_OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> .env
          echo "VITE_PROXY_DOMAIN=${{ secrets.VITE_PROXY_DOMAIN }}" >> .env
          echo "VITE_LEARNING_PLATFORM_API=https://learningapi.nss.team" >> .env
          echo "VITE_COURSE_NAME=${{ secrets.WORKSHOP_NAME }}" >> .env
          echo "BASE_URL=${{ secrets.WORKSHOP_BASE_URL }}" >> .env
          echo "VITE_GLOBAL_PROGRESS_BAR=${{ secrets.WORKSHOP_GLOBAL_PROGRESS_BAR }}" >> .env
          echo "VITE_REQUIRES_GITHUB_AUTHENTICATION=${{ env.REQUIRES_AUTH == 'true' }}" >> .env
    - name: Install dependencies
      run: npm ci

    - name: Build with OAuth variables (if auth enabled)
      if: env.REQUIRES_AUTH == 'true'
      run: npm run build
      env:
        NODE_ENV: production
        VITE_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        VITE_OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        VITE_PROXY_DOMAIN: ${{ secrets.VITE_PROXY_DOMAIN }}

    - name: Build without OAuth variables (if auth disabled)
      if: env.REQUIRES_AUTH == 'false'
      run: npm run build
      env:
        NODE_ENV: production

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Notify Slack of Deployment
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        text: "${{ secrets.WORKSHOP_NAME }} workshop deployment ${{ job.status }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()